### PR TITLE
typo in commands.md and no closing '}' in python example code

### PR DESCRIPTION
**Pull request by R3DDY97**
there is typo in line 239 in docs/commands.md 
WHEREE instead of WHERE

### CODE REVIEW

**Comment by swilly22** [comment]
Thank you,
How come this PR contains so many intermediate commits?

**Comment by R3DDY97** [comment]
No idea 
Maybe it might have come
when i was checking with different branches wehter its already fixed and but not merged 
to  avoid reporting again

**Comment by swilly22** [comment]
Can you please resend this patch, but please branch off from the master branch.

**Comment by R3DDY97** [comment]
0KAY

**Comment by R3DDY97** [comment]
okay 
changed the base branch 
and its clean now

**Comment by swilly22** [comment]
Thank you!

**Pull request merged**
